import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section>
          <div className='flex flex-col-reverse md:flex-row items-center px-6 mx-10 mt-10 space-y-0 md:space-y-0'>
            <div className='flex flex-col mb-32 space-y-12 md: w-1/2'>
              <h1 className='max-w-md text-4xl font-bold text-center md:text-5xl md:text-left'>Your One Stop For Amazing Outfits</h1>
              <p className='max-w-sm text-center text-gray-700 md:text-left'>Perception fashion store is a one-stop shop for all your fashions needs both new and pre- loved wear</p>
              <div className='flex justify-center md:justify-start'>
                <a href='/About' className='p-3 px-6 pt-2 text-white bg-blue-500 rounded-full baseline hover:blue-700'>Explore</a>

                <a href='/Gallery' className='p-3 px-6 pt-2 text-white bg-blue-500 rounded-full baseline hover:blue-700 mx-5'>Gallery</a>

              </div>
            </div>

            <div className='md:w-1/2'>
            <Image
              src="/Image1.png"
              alt="Picture of the author"
              width={500}
              height={500}
              />
            </div>
          </div>
        </section>

        <section>
          <div className='flex flex-col px-4 mx-10 mt-10 space-y-12 md:space-y-0 md:flex-row'>
            <div className='flex flex-col space-y-12 md:w-1/2'>
            <h2 className='max-w-md text-4xl font-bold text-center md:text-left'>
              What's different about Perception Stores?
            </h2>

            <p className='max-w-sm text-center text-gray-700 md:text-left'>
            It all started as a passion for Fashion, grew into a Charity business😅, today we are privileged to have clothed thousands of ladies and counting 🙌. I give it all up to God who found my 3 loaves and two fish worthy to share with multitudes of classy and trendy women.
            </p>
            </div>

            <div className='flex flex-col space-x-8 md:w-1/2'>
              <div className='flex flex-col space-y-3 md:space-y-0 md:space-x-6 md:flex-row'>
                <div className='rounded-l-full bg-blue-200 md:bg-transparent'>
                  <div className='flex items-center space-x-2'>
                    <div className='px-4 py-2 text-white rounded-full md:py-1 bg-blue-900'>01</div>
                    <h3 className='text-base font-bold md:mb-4 md:hidden'>For your styling needs</h3>

                  </div>
                </div>
                <div>
                  <h3 className='hidden mb-4 text-lg font-bold md:block'>For your styling needs</h3>
                  <p className='text-gray-700'>For both official and causual outfit, no matter the time of the year we have the latest outfit trends. Remain stylish be it in a board meeting, hanging out with friends or going on a date, we are that plug you need.</p>
                </div>
              </div>

              <div className='flex flex-col my-4 space-y-3 md:space-y-0 md:space-x-6 md:flex-row'>
                <div className='rounded-l-full bg-blue-200 md:bg-transparent'>
                  <div className='flex items-center space-x-2'>
                    <div className='px-4 py-2 text-white rounded-full md:py-1 bg-blue-900'>02</div>
                    <h3 className='text-base font-bold md:mb-4 md:hidden'></h3>

                  </div>
                </div>
                <div>
                  <h3 className='hidden mb-4 text-lg font-bold md:block'>For your styling needs</h3>
                  <p className='text-gray-700'>For both official and causual outfit, no matter the time of the year we have the latest outfit trends. Remain stylish be it in a board meeting, hanging out with friends or going on a date, we are that plug you need.</p>
                </div>
              </div>

              <div className='flex flex-col space-y-3 md:space-y-0 md:space-x-6 md:flex-row'>
                <div className='rounded-l-full bg-blue-200 md:bg-transparent'>
                  <div className='flex items-center space-x-2'>
                    <div className='px-4 py-2 text-white rounded-full md:py-1 bg-blue-900'>03</div>
                    <h3 className='text-base font-bold md:mb-4 md:hidden'>For your styling needs</h3>

                  </div>
                </div>
                <div>
                  <h3 className='hidden mb-4 text-lg font-bold md:block'>For your styling needs</h3>
                  <p className='text-gray-700'>For both official and causual outfit, no matter the time of the year we have the latest outfit trends. Remain stylish be it in a board meeting, hanging out with friends or going on a date, we are that plug you need.</p>
                </div>
              </div>

              

            </div>
            
          </div>
        </section>

        <section>
          <div className='max-w-6xl px-5 mx-auto mt-32 text-center'>
            <h2 className='text-4xl font-bold text-center'>
              What's the people's Perception?
            </h2>
            <div className='flex flex-col mt-24 md:flex-row md:space-x-6'>
              <div className='flex flex-col items-center p-6 space-y-6 rounded-lg bg-pink-400 md:w-1/3'>
              <Image
              src="/model4.jpg"
              alt="Picture of the author"
              width={200}
              height={200}
              className='w-20 -mt-14 rounded-lg'
              /> 
              <h5 className='text-lg font-bold'>Anita Lo</h5>
              <p className='text-sm text-gray-900'>"Perception Stores came through for me on a short notice with world class outfits on my last show and I recommend them anytime"</p>
                
              </div>

              <div className='hidden flex-col items-center p-6 space-y-6 rounded-lg bg-pink-400 md:w-1/3 md:flex'>
              <Image
              src="/model2.jpg"
              alt="Picture of the author"
              width={200}
              height={200}
              className='w-20 -mt-14 rounded-lg'
              /> 
              <h5 className='text-lg font-bold'>Keysha Cole</h5>
              <p className='text-sm text-gray-900'>"For your comfortable and classy outfits Perception Store have you covered"</p>
                
              </div>

              <div className='hidden flex-col items-center p-6 space-y-6 rounded-lg bg-pink-400 md:w-1/3 md:flex'>
              <Image
              src="/model3.jpg"
              alt="Picture of the author"
              width={200}
              height={200}
              className='w-20 -mt-14 rounded-lg'
              /> 
              <h5 className='text-lg font-bold'>Chamberlain Peace</h5>
              <p className='text-sm text-gray-900'>"The people at Perception Stores are very graceful and welcoming its always fun doing busness at Perception Stores"</p>
                
              </div>
            </div>
          </div> 

          <div className='flex bg-gray-100 mx-auto p-10 mt-10 font-bold'>
            <h1 className='text-black item-center justify-center'>Join the conversation</h1>
            <Link href='https://instagram.com/perceptionstores?igshid=YmMyMTA2M2Y='>
            <Image
              src="/instagram.png"
              alt="Picture of the author"
              width={100}
              height={100}
              className='w-10 rounded-lg mx-5'
              /> 
            
            </Link>

            <Link href='https://api.whatsapp.com/send?phone=%2B2348036888507&data=AWDwVUiS8X_UJ_QFrE69_o2jBWFaAcykZa8k3BEdi5-UV6UArS-0b6cOjPebYBaMQ8IKTcx8O-O1G3R0GvKS55zpWaPOJurrTCD1HHTcaRmeNILegwswekXnN9e1YiGamyDpiQSQ-BsohoMjJl_4e2IWu4F_ogbwk52ouLo9amx4FTH10ePsqpYadIH3ZPW3H7bmXCApR1DW2vBBHDQzt8HF_J7sZzOKuSZsGXOdMu6Kldy797-lQ_juL1yow8BQQ59W6XnmLCqmqg6y1Y0m-q_gS04AvZwDqMvL_st70GXar6CDT6s&source=FB_Page&app=facebook&entry_point=page_cta&fbclid=IwAR1Nyfp_XELBXAUIblvv34BucFgdc-ZTEmdCAZSRLuwGTjid7P_iu_6oVhQ'>
            <Image
              src="/whatsapp.jpg"
              alt="Picture of the author"
              width={200}
              height={200}
              className='w-10 rounded-lg mx-4'
              /> 
            
            </Link>

            <Link href='https://web.facebook.com/perceptionstores/?_rdc=1&_rdr'>
            <Image
              src="/facebook.png"
              alt="Picture of the author"
              width={100}
              height={100}
              className='w-10 rounded-lg mx-5'
              /> 
            
            </Link>
          </div>
          <div>
           

          </div>
        </section>

        <section className='bg-blue-700 mt-10'>
          <div className='flex flex-col items-center justify-between px-6 py-24 mx-auto space-y-12 md:py-12 md:flex-row md:space-y-0'>
          <h2 className='text-5xl font-bold leading-tighttext-center text-white md:text-4xl md:max-w-xl md:text-left'>Your Shopping Needs and Outfits All In One Place</h2>

          <div>
            
          <a href='/Gallery' className='p-3 px-6 pt-2 text-black bg-white rounded-full baseline hover:blue-700 cursor:pointer hover:bg-blue-300 shadow-2xl'>Explore</a>
          

          </div>
          </div>
        </section>

        <footer className='bg-black'>
          <div className='flex flex-col-reverse justify-between px-6 py-10 mx-auto space-y-8 md:space-y-0'>
            <div className='flex flex-col-reverse items-center justify-between space-y-12 md:flex-col md:space-y-0 md:items-start'>
              <div>
              <Image
              src="/logo.jpg"
              alt="Picture of the author"
              width={200}
              height={200}
              className='w-20  rounded-full'
              /> 
              </div>
              <div className='flex justify-center space-x-4'>
                <Link href='#'
                  
                /> 
                
              </div>
            </div>

          </div>
        </footer>
      </div>
    </>
  )
}
